### REST Client test dosyası
# VS Code REST Client eklentisi ile çalışır: https://marketplace.windsurf.com/extension/humao/rest-client
# Gerekli ise baseUrl'i kendi ortamına göre değiştir (ör: Laragon için http://laravel.test)

@baseUrl = http://127.0.0.1:8000
@birimId = 1
@unvanId = 1

### Birimler - Listele
GET {{baseUrl}}/api/birimler
Accept: application/json

### Birimler - Oluştur
POST {{baseUrl}}/api/birimler
Content-Type: application/json
Accept: application/json

{
  "birim_adi": "Mali işler",
  "konumu": "Ankara"
}

### Birimler - Göster
GET {{baseUrl}}/api/birimler/{{birimId}}
Accept: application/json

### Birimler - Güncelle (PATCH)
PATCH {{baseUrl}}/api/birimler/{{birimId}}
Content-Type: application/json
Accept: application/json

{
  "birim_adi": "Ar-Ge",
  "konumu": "İzmir"
}

### Birimler - Sil
DELETE {{baseUrl}}/api/birimler/{{birimId}}
Accept: application/json

### Unvanlar - Listele
GET {{baseUrl}}/api/unvanlar
Accept: application/json

### Unvanlar - Oluştur
POST {{baseUrl}}/api/unvanlar
Content-Type: application/json
Accept: application/json

{
  "unvan_adi": "profesyonel"
}

### Unvanlar - Göster
GET {{baseUrl}}/api/unvanlar/{{unvanId}}
Accept: application/json

### Unvanlar - Güncelle (PATCH)
PATCH {{baseUrl}}/api/unvanlar/{{unvanId}}
Content-Type: application/json
Accept: application/json

{
  "unvan_adi": "Kıdemli Uzman"
}

### Unvanlar - Sil
DELETE {{baseUrl}}/api/unvanlar/{{unvanId}}
Accept: application/json

@personelId = 1

### personel - Listele
GET {{baseUrl}}/api/personel
Accept: application/json

### personel - Oluştur
POST {{baseUrl}}/api/personel
Content-Type: application/json
Accept: application/json

{
  "adi_soyadi": "Ali Veli",
  "unvan_id": 1,
  "birim_id": 2,
  "notlar": "Deneme personel kaydı"
}

### personel - Göster
GET {{baseUrl}}/api/personel/{{personelId}}
Accept: application/json

### personel - Güncelle (PATCH)
PATCH {{baseUrl}}/api/personel/{{personelId}}
Content-Type: application/json
Accept: application/json

{
  "adi_soyadi": "Ali Veli Demir",
  "unvan_id": 1,
  "birim_id": 1,
  "notlar": "Güncellenmiş not"
}

### personel - Sil
DELETE {{baseUrl}}/api/personel/{{personelId}}
Accept: application/json
